# Sentinel Crypto Agent configuration file
default_pair: BTC/USDC
exchange: binance
strategies:
  - EMA20_100
  - Donchian20
  - BollingerSqueeze
  - IchimokuKumo
  - MACDZeroCross
  - VWAPPullback
  - KeltnerUpperRide
  - SMA50Pullback
  - SARFlip
  - RSIDivergence
fees: 0.0005  # 0.05%
slippage: 0.0005
position_size_pct: 0.01  # 1% capital
delta_be: 0.0015  # 0.15% move to arm trailing stop
trailing_pct: 0.008  # 0.8% trailing stop distance
